# vim: ft=yaml.docker-compose
name: step-ca

include:
  - ext/docker-compose-snippets/tailscale.yaml

services:
  step-ca:
    image: smallstep/step-ca:latest
    environment:
      DOCKER_STEPCA_INIT_NAME: step-ca
      DOCKER_STEPCA_INIT_DNS_NAMES: step-ca.ipn.rahulsalvi.com
      DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT: true
    volumes:
      - step-data:/home/step
    restart: unless-stopped
    extends:
      file: ext/docker-compose-snippets/tailscale-app-base.yaml
      service: tailscale-app-base

volumes:
  step-data:


secrets:
  ts_authkey:
    file: ./ts_authkey.txt
